# Generated by Django 4.0 on 2021-12-24 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facultacy_name', models.CharField(max_length=50, verbose_name='Название факультета')),
                ('passing_score', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Проходной балл')),
                ('is_growing', models.BooleanField(verbose_name='Увеличивается ли проходной балл?')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Когда последний раз обновлялась информация о проходном балле?')),
            ],
        ),
    ]
